### PR TITLE
Fixing issue where scrollPos was not defined

### PR DESCRIPTION
**Pull request by psbanka**
To solve issue https://github.com/webdriverio/webdrivercss/issues/63

### CODE REVIEW

**Comment by TheSavior** [comment]
Thanks for contributing! I'm not super confident about this part of the codebase, but my intuition is that this is a bug with `getPageInfo` not always providing a scrollPos and should be fixed there instead of in `cropImage`.

@christian-bromann thoughts?

**Comment by christian-bromann** [comment]
@psbanka thanks for contributing!

Could you please take a look [here](https://github.com/webdriverio/webdrivercss/blob/master/lib/getPageInfo.js#L36-L64)? Seems that your browser/platform combination has problems getting the scroll position as @TheSavior mentioned

**Comment by psbanka** [comment]
Thanks for the feedback. I'll get back to you shortly.

**Comment by psbanka** [comment]
@christian-bromann not sure why the build is failing, but I modified the fix to focus on `getPageInfo` instead of `cropImage`

**Comment by christian-bromann** [comment]
@psbanka don't worry about the build for now. Could you instead of setting default values just default to `0` at [that](https://github.com/psbanka/webdrivercss/blob/exclude-rect-without-scroll/lib/getPageInfo.js#L64-L65) position (e.g. `x: x || 0`) since `window.pageYOffset` can return `undefined`. Then you could get rid of that additional if

**Comment by psbanka** [comment]
My mistake; I forgot to remove the `if`. The default `response` value on line 22 of `lib/getPageInfo.js` solves the problem. Thanks for your patience.

**Comment by christian-bromann** [comment]
@psbanka one single thing: please remove [line 23 and 24](https://github.com/psbanka/webdrivercss/blob/exclude-rect-without-scroll/lib/getPageInfo.js#L23-L25) otherwise it will throw an error ;-)

**Comment by psbanka** [comment]
How embarrassing.. :persevere:

**Comment by psbanka** [comment]
@christian-bromann I believe this is resolved.

**Comment by christian-bromann** [comment]
@psbanka yes it is, sorry for the delay

**Comment by christian-bromann** [comment]
@psbanka This just got published with `v1.1.0`

**Pull request merged**
