### PR TITLE
Prevent webdrivercss() from modifying an array passed to it.

### PR DESCRIPTION
**Pull request by brettle**
The commit includes a new test which failed before the fix. Let me know if you need more info.

### CODE REVIEW

**Comment by christian-bromann** [comment]
@brettle thanks for contributing! I don't quite understand the fix as the test passed in the last build and on my local machine.

**Comment by brettle** [comment]
The commit has both the test and the fix. To see the test fail, revert the change I made to lib/workflow.js.

Note that this has _nothing_ to do with the issue I recently reported with one of the existing tests failing.

**Comment by christian-bromann** [comment]
ohh now I see the issue here. You've passed in a variable and that variable changed after executing the webdrivercss command. Should have read the issue title before looking at the change :smile:

**Comment by brettle** [comment]
This PR now includes a simple workaround for the unrelated failing test mentioned in issue #76. Sorry for combining PRs, but its probably easier to merge both in one shot anyway.

**Comment by christian-bromann** [comment]
Awesome, thanks!

**Comment by christian-bromann** [comment]
published with `v1.1.4`

**Pull request merged**
