### PR TITLE
Add webdriverio 3 API compatibility

### PR DESCRIPTION
**Pull request by benurb**
Hello!

we saw that you're already working on webdriverio 3 compatibility on the 1.2 version branch, but it's a huge rework to migrate from async to q in one release. As we wanted to use the improvements of wdio 3 in our projects we created an implementation on our webdrivercss fork, that just changes the minimum amount of code needed to update wdio. Basically we changed the following things:
1. Update calls to wdio to reflect the changes done in version 3
2. Change custom commands to return q promises instead of using the callback needed by wdio 2
Naturally it's a **breaking change** for users of webdrivercss, because of the API differences in wdio.

Of course we wanted to share our work with you and maybe you can use it as base to get wdio 3 support out soon. Keep up the great work :+1: 

Best regards
@sagold & @benurb

### CODE REVIEW

**Comment by wbeard** [comment]
:+1:

**Comment by klamping** [comment]
Just tested this out on my box and it's mostly working. I did notice that [defining the webdrivercss options via the wdio.conf.js file](https://github.com/webdriverio/webdriverio/blob/master/examples/wdio/wdio.webdrivercss.conf.js#L25) doesn't work. I had to manually pass them by running:
`require("webdrivercss").init(browser, browser.options.plugins.webdrivercss);`

Other than that, I plan on using this branch moving forward, so that I can get the benefits of wdio 3.x while still keeping webdrivercss.

**Comment by christian-bromann** [comment]
Merged that branch into `v2.0.0beta-rc1` and published it to npm (with that version). What I actually want to see for v2 is to completely remove the `async` library.

**Comment by benurb** [comment]
Yep, I know. That should be the goal, but now there is some base to work on :+1:

**Comment by klamping** [comment]
Just wanted to say thanks to @christian-bromann for getting the beta release out, and to @benurb for taking the time to make the PR to begin with.

**Comment by chris-gunawardena** [comment]
Thanks Chrisian, this branch looks good. I setup a easy to use test project here: https://github.com/chris-gunawardena/grunt-webdrivercss-example

One thing I noticed was it always takes a full page screenshot of the url as well as the selectors. (this is not used for comparisons and gets recreated every time). Not sure if this is intended but can be useful as reference. But it does take time to scan long pages.

**Comment by talitore** [comment]
@christian-bromann Is it possible to get this rebased and published (`rc2 maybe`)? I rebased it locally and all tests are green. The reason I ask is I'm needing the `ignore: 'antialiasing'` functionality. Let me know if I can help at all.

**Comment by christian-bromann** [comment]
@benurb thanks again for the work you put into this PR/project. After working on the other projects I will now cycle back to WebdriverCSS in order to get this project back on its feed. To stay aligned with the structure of the other packages, I will use babel and async/await for asynchronous handling.

**Pull request closed without merging**
