### PR TITLE
WebdriverIO v4 compatibility fix

### PR DESCRIPTION
**Pull request by denis-kudelin**
WebdriverIO v4 compatibility fix + Added the ability to set gm options

### CODE REVIEW

**Comment by rgustavsson** [comment]
Looking forward to see this merge! :)

**Comment by rgustavsson** [comment]
Come on Denis, you can do it :D

**Comment by christian-bromann** [comment]
Denis can't merge this PR and I unfortunately can't do it either because we are planning a new direction for WebdriverCSS

**Comment by rgustavsson** [comment]
Whats the new direction @christian-bromann? :)

**Comment by christian-bromann** [comment]
see https://github.com/zinserjan/wdio-screenshot/issues/5

**Pull request closed without merging**
