### PR TITLE
[BUG] Fix ability to sync nested repos

### PR DESCRIPTION
**Pull request by kevinmcdonnell**
Fix for issue #124

### CODE REVIEW

**Comment by christian-bromann** [comment]
@kevinmcdonnell can we add a unit test or something similar?

**Comment by kevinmcdonnell** [comment]
@christian-bromann I've added some tests

**Comment by christian-bromann** [comment]
Could you fix the indention?

**Comment by kevinmcdonnell** [comment]
@christian-bromann Apologies for the delay, I actually can't see an issue with indentation anywhere... Can you point it out if I'm missing something?

https://github.com/webdriverio/webdrivercss/pull/125/files#diff-e69eee6ae3f84a105138401115839e08L56 moved to https://github.com/webdriverio/webdrivercss/pull/125/files#diff-e69eee6ae3f84a105138401115839e08R72

**Pull request closed without merging**
